# Generated by Django 3.2 on 2021-07-05 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='app_url',
            field=models.CharField(default='#', max_length=100),
            preserve_default=False,
        ),
    ]
