# Generated by Django 3.2 on 2021-07-05 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_app_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='image_name',
            field=models.CharField(default='image', max_length=50),
            preserve_default=False,
        ),
    ]
